# Generated by Django 4.1.3 on 2022-11-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_teamleader',
            field=models.BooleanField(default=False),
        ),
    ]
