# Generated by Django 4.1.3 on 2022-12-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_schedules_userschedules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedules',
            old_name='end',
            new_name='ending',
        ),
    ]
