# Generated by Django 4.1.3 on 2022-12-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_end_schedules_ending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='beginning',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='ending',
            field=models.DateTimeField(),
        ),
    ]
