# Generated by Django 4.1.3 on 2022-12-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_schedules_beginning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='beginning',
            field=models.DateTimeField(unique=True),
        ),
    ]
