# Generated by Django 4.1.3 on 2022-12-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_schedules_beginning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='beginning',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='ending',
            field=models.DateTimeField(unique=True),
        ),
    ]
